AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WelcomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: FCG.Notifications.WelcomeLambda::FCG.Notifications.WelcomeLambda.Function::FunctionHandler
      Runtime: dotnet8
      CodeUri: ./
      MemorySize: 256
      Timeout: 30